inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.2
  Exclude:
    - 'bin/**'
    - 'config/deploy/*.rb'
    - 'vendor/**/*'

# because we won't have many gems so a more "semantic" ordering will work
Bundler/OrderedGems:
  Exclude:
    - 'Gemfile'

# because we have code that is clearer this way
Metrics/AbcSize:
  Exclude:
    - 'lib/sparql_to_sw_solr/instance_title_fields.rb'

Metrics/BlockLength:
  Exclude:
    - 'spec/**'

# because some of these methods will need to be a bit complex to deal with punctuation
Metrics/CyclomaticComplexity:
  Max: 10

# because this isn't 1970
Metrics/LineLength:
  Max: 120
  Exclude:
    - 'spec/instance_solr_doc_spec.rb'

# because some of these methods will need to be long
Metrics/MethodLength:
  Exclude:
    - 'lib/sparql_to_sw_solr/instance_title_fields.rb'

# because some of these methods will need to be a bit complex to deal with punctuation
Metrics/PerceivedComplexity:
  Max: 10
  
# because the complexity of this app and its classes shouldn't require this with good naming
Style/Documentation:
  Enabled: false

# because it can make the code more skimmable/readable
Style/EmptyLinesAroundBlockBody:
  Enabled: false

# because it can make the code more skimmable/readable
Style/EmptyLinesAroundClassBody:
  Enabled: false

# because it can make the code more skimmable/readable
Style/EmptyLinesAroundModuleBody:
  Enabled: false

# because it doesn't make it more readable
Style/RegexpLiteral:
  Enabled: false

Style/SpaceInsideStringInterpolation:
  Exclude:
    - 'lib/sparql_to_sw_solr/instance_title_fields.rb'

# because it's silly to care
Style/StringLiterals:
  Enabled: false

# because it doesn't make it more readable
Style/WordArray:
  EnforcedStyle: brackets
