inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.2
  Exclude:
    - 'bin/**'
    - 'config/deploy/*.rb'
    - 'vendor/**/*'

# because we won't have many gems so a more "semantic" ordering will work
Bundler/OrderedGems:
  Exclude:
    - 'Gemfile'

# because field values have concatenation and punctuation
Metrics/AbcSize:
  Exclude:
    - 'lib/sparql_to_sw_solr/instance_title_fields.rb'
    - 'lib/sparql_to_sw_solr/instance_pub_fields.rb'

Metrics/BlockLength:
  Exclude:
    - 'spec/**'

# because methods deal with punctuation
Metrics/CyclomaticComplexity:
  Exclude:
    - 'lib/sparql_to_sw_solr/instance_pub_fields.rb'

# because this isn't 1970
Metrics/LineLength:
  Max: 120
  Exclude:
    - 'spec/instance_solr_doc_spec.rb'

# because methods assigning many fields can still be clear if a little longer
# and because field values have concatenation and punctuation
# and because sparql queries can be long
Metrics/MethodLength:
  Max: 13
  Exclude:
    - 'lib/sparql_to_sw_solr/instance_pub_fields.rb'

# because there is logic for three separate publication related fields, and it's < 200 lines
Metrics/ModuleLength:
  Exclude:
    - 'lib/sparql_to_sw_solr/instance_pub_fields.rb'

# because pub_search method is already at a sweet spot for refactoring vs readability
Metrics/PerceivedComplexity:
  Exclude:
    - 'lib/sparql_to_sw_solr/instance_pub_fields.rb'

# because the simplicity of this app and its classes shouldn't require this with good naming
Style/Documentation:
  Enabled: false

# because it can make the code more skimmable/readable
Style/EmptyLinesAroundBlockBody:
  Enabled: false

# because it can make the code more skimmable/readable
Style/EmptyLinesAroundClassBody:
  Enabled: false

# because it can make the code more skimmable/readable
Style/EmptyLinesAroundModuleBody:
  Enabled: false

# because it doesn't make the spec more readable
Style/MixinGrouping:
  Exclude:
    - 'spec/instance_pub_fields_spec.rb'

# because it doesn't make it more readable
Style/RegexpLiteral:
  Enabled: false

# because it's silly to care
Style/StringLiterals:
  Enabled: false

# because it doesn't make it more readable
Style/WordArray:
  EnforcedStyle: brackets
